package com.netty.entity;

// Generated 2015-8-27 11:17:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TChatlog generated by hbm2java
 */
@Entity(name = "t_chatlog")
public class TChatlog implements java.io.Serializable {

	private String id;
	private TUsers TUsers;
	private Integer fid;
	private String chatContent;
	private Date chatTime;
	private Integer isRead;

	public TChatlog() {
	}

	public TChatlog(String id) {
		this.id = id;
	}

	public TChatlog(String id, TUsers TUsers, Integer fid, String chatContent,
			Date chatTime, Integer isRead) {
		this.id = id;
		this.TUsers = TUsers;
		this.fid = fid;
		this.chatContent = chatContent;
		this.chatTime = chatTime;
		this.isRead = isRead;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public TUsers getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(TUsers TUsers) {
		this.TUsers = TUsers;
	}

	@Column(name = "FId")
	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	@Column(name = "ChatContent")
	public String getChatContent() {
		return this.chatContent;
	}

	public void setChatContent(String chatContent) {
		this.chatContent = chatContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChatTime", length = 19)
	public Date getChatTime() {
		return this.chatTime;
	}

	public void setChatTime(Date chatTime) {
		this.chatTime = chatTime;
	}

	@Column(name = "IsRead")
	public Integer getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Integer isRead) {
		this.isRead = isRead;
	}

}
