package com.netty.entity;

// Generated 2015-8-27 11:17:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TUsers generated by hbm2java
 */
@Entity(name = "t_users")
public class TUsers implements java.io.Serializable {

	private String id;
	private Integer userId;
	private String userName;
	private String userNick;
	private String passWord;
	private String email;
	private String tel;
	private Date birthday;
	private String address;
	private Set<TFriendlist> TFriendlistsForUserId = new HashSet<TFriendlist>(0);
	private Set<TFriendlist> TFriendlistsForFid = new HashSet<TFriendlist>(0);
	private Set<TChatlog> TChatlogs = new HashSet<TChatlog>(0);

	public TUsers() {
	}

	public TUsers(String id) {
		this.id = id;
	}

	public TUsers(String id, Integer userId, String userName, String userNick,
			String passWord, String email, String tel, Date birthday,
			String address, Set<TFriendlist> TFriendlistsForUserId,
			Set<TFriendlist> TFriendlistsForFid, Set<TChatlog> TChatlogs) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.userNick = userNick;
		this.passWord = passWord;
		this.email = email;
		this.tel = tel;
		this.birthday = birthday;
		this.address = address;
		this.TFriendlistsForUserId = TFriendlistsForUserId;
		this.TFriendlistsForFid = TFriendlistsForFid;
		this.TChatlogs = TChatlogs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "UserId", unique = true)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName", length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserNick", length = 30)
	public String getUserNick() {
		return this.userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	@Column(name = "PassWord", length = 30)
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@Column(name = "Email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Tel", length = 30)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Address", length = 30)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUsersByUserId")
	public Set<TFriendlist> getTFriendlistsForUserId() {
		return this.TFriendlistsForUserId;
	}

	public void setTFriendlistsForUserId(Set<TFriendlist> TFriendlistsForUserId) {
		this.TFriendlistsForUserId = TFriendlistsForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUsersByFid")
	public Set<TFriendlist> getTFriendlistsForFid() {
		return this.TFriendlistsForFid;
	}

	public void setTFriendlistsForFid(Set<TFriendlist> TFriendlistsForFid) {
		this.TFriendlistsForFid = TFriendlistsForFid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUsers")
	public Set<TChatlog> getTChatlogs() {
		return this.TChatlogs;
	}

	public void setTChatlogs(Set<TChatlog> TChatlogs) {
		this.TChatlogs = TChatlogs;
	}

}
